easy_admin:
  site_name: 'LuckyLottoNumber'
  entities:
        Country:
            class: App\Entity\Country
        Lotto:
            class: App\Entity\Lotto
        Result:
            class: App\Entity\Result
